### ISSUE TITLE
useState의 함수형 업데이트 유무에 대한 useEffect 경고문 차이에 대한 고찰

### ISSUE THREAD

**Issue by whitecity01** [mingking2/FE-React-Study#23]
`# `useState`의 함수형 업데이트 유무의 차이에 대한 고찰

**발단** : 왜 1번째는 오류문구가 뜨고 2번째 코드는 안뜰까?

![image01](https://github.com/mingking2/FE-React-Study/assets/122271925/8c5f72b6-30c2-4784-a6ea-2311acd123b5)

이유를 알기에 앞서 두 코드에 대해서 분석해보자.

**1번째 코드**:
1. 처음 화면이 랜더링 될 때, useEffect가 실행된다.
2. countState가 실행된다.
3. 기존의 count값 0을 가져와 +1 연산을 실시한다
4. state가 변경되었기에 state 값의 변경을 확인하고, 변경되었다면 랜더링을 실시한다.
5. 화면에 바뀐 count값 1이 출력이 된다.
6. useEffect는 빈 배열을 갖기에 state의 변화에 관련없이 이제 호출되지 않는다.
여기까지가 1번째 코드의 파일을 실행했을 때의 간략한 과정이다.

**2번째 코드(함수형 업데이트)**:
1. 처음 화면이 랜더링 될 때, useEffect가 실행된다.
2. countState가 실행된다.
3. 이전의 count값(랜더링 되지 않은, 최신의 상태값) 0을 가져와 +1 연산을 실시한다
4. state가 변경되었기에 state 값의 변경을 확인하고, 변경되었다면 랜더링을 실시한다.
5. 화면에 바뀐 count값 1이 출력이 된다.
6. useEffect는 빈 배열을 갖기에 state의 변화에 관련없이 이제 호출되지 않는다.
여기까지가 2번째 코드의 파일을 실행했을 때의 간략한 과정이다.

뭐야 별 차이 없는데? 라고 생각할 수 있는데 맞는 말이다.

왜 두 코드의 경고문 유무가 다르지를 묻기에는 사실 위의 동작과정이 크게 관련이 없다.

**결론**:

첫 번째 코드만 경고문이 뜨는 이유는 ”useEffect 안에서 상태값인 count가 직접적으로 사용되었기 때문에 그에 따른 의존성 배열을 사용해야 할 것 같다“ 라는 vscode의 친절한 경고문이 출력된 것이고,

두 번째 코드에 경고문이 뜨지 않는 이유는 함수형 업데이트를 통해 prevCount라는 인자에 count의 최신 상태값을 인자로 가져와 상태를 업데이트 한 것이기 때문에 useEffect에서 이를 인지를 못하기 때문에 경고문이 출력되지 않는 것이다.

## `부록`

*이대로 보고서를 끝내기엔 공부한 내용이 아까워서 추가적으로 작성해 봤습니다*

![image02](https://github.com/mingking2/FE-React-Study/assets/122271925/48363642-277a-429f-b5be-5fb1b6b93e9b)

**다음과 같은 코드의 실행 결과는 어떻게 될까요?**

정답 : 1

**이유**:    
1. setState는 비동기함수이다
2. 리액트는 여러개의 상태 값 변경 요청을 랜더링 시 일괄 처리한다. <- 성능 이슈
3. 따라서 코드가 돌아갈 때, value값은 항상 상태값 변경이 안된 0 값을 가지고 있기 때문에 setValue(value+1)은 항상 0+1 = 1이 된다.
4. 따라서 1이 출력이 된다.      
    
    

![image04](https://github.com/mingking2/FE-React-Study/assets/122271925/9a2107bc-d698-46ee-af6e-c9db6e257487)

**다음과 같은 코드의 실행 결과는 어떻게 될까요?**

정답 : 3

**이유**:
1. 이 방법은 비동기적 특성을 지닌 setState 함수를 동기적으로 사용하는 방법인 함수형 업데이트 방법이다.
2. prev라는 인자에 상태값인 value의 최신 값을 가져와 연산을 실시한다.
3. 마지막 setValue까지 코드가 돌 때까지, value의 값은 0이지만 인자로 들어가는 prev는 값이 최신화 되고 있기 때문에 3이라는 값이 출력되게 된다.
4. 따라서, 함수형 업데이트를 사용하면 그 인자에 state의 이전 상태(제일 최신)값이 들어가게 되어 동기적 처리가 가능하게 된다.

![image03](https://github.com/mingking2/FE-React-Study/assets/122271925/fb47a40b-c295-47c8-84b3-0ab2bf68c527)

**Q1. 이 코드의 valueX와 valueY의 출력 결과는 어떻게 될까요?**

정답 : valueX : 2 , valueY: 1

설명은 필요없겠죠?

**Q2. 이 코드의 랜더링! 출력 횟수는 몇 번일까요?**

정답 : 1번

이유 : 성능 문제로 리액트는 한꺼번에 setState의 업데이트를 진행하여 리랜더링 되기 때문에 1번만 실시 됩니다.`

**Comment by BangDori** [comment]
롤만 잘하는게 아니라, 공부도 잘하네

**Comment by sangjung0** [comment]
멋져요!

**Comment by Tentennball** [comment]
지렸다 브로!

**Comment by mingking2** [comment]
오타 수정해주세요 
설명 쳐직이네 굳굳

**Comment by ches0703** [comment]
Good
