### ISSUE TITLE
왜 index 값을 key로 사용하면 리렌더링이 비효율적인가?

### ISSUE THREAD

**Issue by mingking2** [mingking2/FE-React-Study#27]
예시 코드를 들어서 설명하자

아래 코드는 `index`를 key로 사용하는 예시 코드이다.
```jsx
import React, { useState } from 'react';

const ExampleComponent = () => {
  const [items, setItems] = useState(['apple', 'banana', 'orange']);

  const handleRemove = (index) => {
    const updatedItems = [...items];
    updatedItems.splice(index, 1);
    setItems(updatedItems);
  };

  return (
    <div>
      <h2>Items List</h2>
      <ul>
        {items.map((item, index) => (
          <li key={index}>
            {item}
            <button onClick={() => handleRemove(index)}>Remove</button>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default ExampleComponent;
```

- 위의 예시 코드는 items라는 배열의 각 요소를 리스트로 보여주는 컴포넌트이다. 
- 각 요소 뒤에는 삭제 버튼이 있어서 해당 요소를 제거할 수 있다.

**하지만 이 코드에서는 index를 key로 사용하고 있기 때문에 다음과 같은 문제가 발생할 수 있다.**

 1. **리렌더링 문제**: 배열의 요소가 추가되거나 삭제될 때, index가 변경되어 모든 요소가 리렌더링된다. 
    -  이 예시에서는 배열의 첫 번째 요소가 삭제되면 나머지 요소들의 index가 변경되어 모든 요소가 리렌더링된다.

 2. **순서 변경 문제**: 배열의 순서가 변경되는 경우에도 모든 요소가 리렌더링된다. 
    - 예를 들어, 배열의 요소들이 [apple, banana, orange]에서 [banana, orange, apple]로 순서가 변경되면 모든 요소가 리렌더링된다.

-> 이러한 문제로 인해 불필요한 성능 저하가 발생하고, 예상치 못한 동작이 발생할 수 있다.

> 따라서 배열의 요소들이 고유한 ID나 고유한 값을 가지고 있는 경우, 해당 값을 key로 사용하는 것이 좋다. 
예를 들어, items 배열의 각 요소들이 고유한 ID를 가지고 있다면, 해당 ID를 key로 사용하면 된다. 
이렇게 하면 배열의 요소들이 변경되어도 해당 요소만 업데이트되며, 다른 요소들은 그대로 유지된다.
이렇게 key를 사용하면 리액트가 효율적으로 리렌더링되고, 성능에 더 나은 영향을 미친다.

**Comment by whitecity01** [comment]
good

**Comment by ches0703** [comment]
Good

**Comment by Tentennball** [comment]
굿!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hotteok00** [comment]
good

**Comment by BangDori** [comment]
고생했슴니당~
